package Presenter;

public enum Events {
    ADD_USER, REPORTS,PROPERTIES,ADD_USERS_POP_MENU,SAVE_USER,EXIT, REGISTER_USER, ADD_HOUSE,ADD_BUILDING,ADD_APARTMENT,  SHOW_PROPERTIES_PANEL,SHOW_USERS_PANEL;;
}
